/* iniciando programação com sql */

CREATE PROCEDURE NOME()
BEGIN

    /* QUALQUER BLOCO DE PROGRAMAÇÃO*/

END
$ /* DELIMITADOR NOVO, DEFINIDO NO ARQUIVO PASSADO */


CREATE PROCEDURE NOME_EMPRESA()
BEGIN
    SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESAS;
END
$


CALL NOME_EMPRESA()$

CREATE PROCEDURE CONTA()
BEGIN 

    SELECT 10 + 10 AS CONTA;
END$

CALL CONTA()$

DROP PROCEDURE CONTA$

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN 
    SELECT NUMERO1 + NUMERO2 AS CONTA;
END$

CALL CONTA(10, 10)$

CREATE DATABASE ESCOLA$

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);$

INSERT INTO CURSOS VALUES(NULL,'JAVA',30,500.00)$
INSERT INTO CURSOS VALUES(NULL,'FUNDAMENTOS DE BANCOS DE DADOS',40,700.00)$

CREATE PROCEDURE CADASTRO(P_NOME VARCHAR(30), P_HORAS INT(3), P_VALOR FLOAT(10,2))
BEGIN 
    INSERT INTO CURSOS(IDCURSO, NOME, HORAS, VALOR) VALUES (NULL, P_NOME, P_HORAS, P_VALOR);
END$

CALL CADASTRO('CURSO DE BANCO DE DAOS E SQL', 60, 27.99)$
CALL CADASTRO('POWER BI', 20, 27.99)$

CREATE PROCEDURE CONSULTAR()
BEGIN
    SELECT * FROM CURSOS;
END$

CALL CONSULTAR()$