CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F')DEFAULT 'M',
    EMAIL VARCHAR(30) UNIQUE,
    CPF CHAR(11) NOT NULL UNIQUE  
);

CREATE TABLE ENDERECO( /*TABELA MAIS FRACA*/
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    UF CHAR(2) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    RUA VARCHAR(30) NOT NULL,
    FK_CLIENTE INT UNIQUE,
    FOREIGN KEY(FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE TELEFONE(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    FK_CLIENTE INT,
    FOREIGN KEY(FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

SELECT * FROM CLIENTE;

DESC ENDERECO;

INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

/* ERROR - FK_CLIENTE ESTÁ DUPLICADA */
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA ALFANDEGA','CENTRO','SAO PAULO','SP',5);

SELECT * FROM ENDERECO;

DESC TELEFONE;

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);

SELECT * FROM TELEFONE;

SELECT FK_CLIENTE, COUNT(*) FROM TELEFONE GROUP BY FK_CLIENTE;

/* EXERCICIOS DML */

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');
INSERT INTO CLIENTE VALUES(NULL,'GIU','F','GIU@GMAIL.COM','17389149760');

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDERECO(ID_ENDERECO, RUA, BAIRRO, CIDADE, UF, FK_CLIENTE) VALUES(NULL,'RUA NILZA','CENTRO','RIO DE JANEIRO','RJ',21);

/* CADASTRE TELEFONES PARA OS CLIENTES */


INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','965836182',21);

/* RELATÓRIO GERAL DE TODOS OS CLIENTES */

SELECT *
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E
ON C.ID_CLIENTE = E.FK_CLIENTE;

/* RELAT;ORIO DOS HOMENS */
SELECT C.NOME, C.CPF, T.NUMERO, E.CIDADE
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E
ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE SEXO = 'M';

/* RELAT;ORIO DAS MULHERES */
SELECT C.NOME, C.CPF, T.NUMERO, E.CIDADE
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.ID_CLIENTE = T.FK_CLIENTE
INNER JOIN ENDERECO E
ON C.ID_CLIENTE = E.FK_CLIENTE
WHERE SEXO = 'F';

/* QUANTIDADE DE HOMENS E MULHERES */

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE NOME IN ('CELIA', 'LORENA', 'ELAINE', 'CARMEM', 'KARLA', 'DANIELE');

UPDATE CLIENTE
SET SEXO = 'M'
WHERE NOME IN ('ANTONIO');


/* IDs E EMAILs DE MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO QUE NÃO TENHAM CELULAR */

SELECT C.ID_CLIENTE AS ID, C.EMAIL
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.ID_CLIENTE = E.FK_CLIENTE
INNER JOIN TELEFONE T
ON C.ID_CLIENTE = T.FK_CLIENTE
WHERE E.UF = 'RJ' AND E.BAIRRO = 'CENTRO' 
AND C.SEXO= 'F'
AND (T.TIPO = 'RES' OR T.TIPO = 'COM');

